print("Benvenuti al programma \"Moltiplicatore\"!")
print("Restituisce in output il risultato di una moltiplicazione tra due numeri!\n")
primo_valore = input("Inserisci il primo valore --> ")
secondo_valore = input("Inserisci il secondo valore --> ")
risultato = int(primo_valore) * int(secondo_valore)
print("Il risultato della moltiplicazione è: ", float(risultato))
